# Generated by Django 5.1.4 on 2025-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(verbose_name='Employee Number')),
                ('ename', models.CharField(max_length=20, verbose_name='Employee Name')),
                ('esal', models.FloatField(verbose_name='Employee Salary')),
            ],
        ),
    ]
