# Generated by Django 5.1.4 on 2025-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name :')),
                ('cust_addr', models.TextField(verbose_name='Customer Address :')),
                ('cust_contact', models.BigIntegerField(verbose_name='Customer Contact :')),
            ],
        ),
    ]
